### ISSUE TITLE
Preformance seems to be poor in benchmark.

### ISSUE THREAD

**Issue by cloudhan** [NVIDIA/triton-inference-server#1637] opened 2020-06-09 09:36 UTC
**Description**
A benchmark is present on https://dev.to/kemingy/deep-learning-serving-benchmark-1nko and triton has the worst performance. Info and code can be obtained from https://gist.github.com/kemingy/a382528b29f6e34c47b464cf16806731

Any preformance tips?

**Triton Information**
As in https://gist.github.com/kemingy/a382528b29f6e34c47b464cf16806731

**To Reproduce**
Follow https://gist.github.com/kemingy/a382528b29f6e34c47b464cf16806731

**Expected behavior**
Higher performace!

**Comment by deadeyegoodwin** [comment] 2020-06-09 17:34
The benchmark isn't very clear about exactly what resnet model they are using but we can assume that it is some TF variant since it runs on TensorFlow. 

Benchmarks are tricky things as it is easy to unfairly compare unless you are very careful (and even then it is challenging...). Just from looking briefly at this I notice that they seem to compare some solutions that go though a GRPC or HTTP endpoint vs. ones that directly run the model. This is unfair as the GRPC or HTTP endpoint can add significant overhead. Their test client also seems to only send 1 request at a time, synchronously... that is no way to measure throughput as much of the time the inference server will just be waiting for the next request.

We provide perf_client for these and other reasons so that you can easily measure performance yourself under the conditions that are important to you. The optimization section in the docs talks about perf_client: https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/optimization.html.

Again, I can't tell exactly what model they ran but with an fp32 version of a TF resnet50 model using 1 request in flight (concurrency == 1 in perf_client terminology) and batch 32 to match what they did:

$ perf_client -m resnet_v1_50_savedmodel --concurrency-range 1 -b32

I see ~650 infer/sec which is ~49 secs by their metric. But if you really wanted maximum throughput you should give Triton more than 1 inference request at a 1 time (you would also want to experiment with dynamic batcher and multiple model instances but I'll leave that to you):

$ perf_client -m resnet_v1_50_savedmodel --concurrency-range 4 -b32

Gives ~1050 infer/sec which is ~30 seconds by their metric.

We have some performance testing that we use to recognize regressions and we are working on some automation to be able to publish those numbers with each release so that there is a more direct resource available for you to get some understanding of Triton performance.

**Comment by ldengjie** [comment] 2020-06-19 04:09
Hi, I have also noticed that bechmark, the author used a bad parameter:
https://gist.github.com/kemingy/a382528b29f6e34c47b464cf16806731#file-triton_client-py-L21
"output.cls.count" means the topn result after sorted by triton server.
If let output.cls.count=0 to disable the sort, the server will return the whole raw result, and the performance will be normal.

**Comment by deadeyegoodwin** [comment] 2020-06-19 15:49
@ldengjie  Good point!
Closing... keep an eye out for us to provide some perf numbers in the README or docs later this year.

**Closed by deadeyegoodwin** 2020-06-19 15:49 UTC
