### ISSUE TITLE
gRPC communication extremely slow

### ISSUE THREAD

**Issue by DonnieKim411** [NVIDIA/triton-inference-server#1821] opened 2020-07-23 05:12 UTC
**Description**

I am following the Triton image classification example (https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client_example.html#section-image-classification-example) but when i use gRPC protocol, it is extremely slow

**Triton Information**
What version of Triton are you using?

20.06

Are you using the Triton container or did you build it yourself?

The pre-built Triton container

**To Reproduce**
Steps to reproduce the behavior.

1. run the triton server using the following simple script:

```
#!/bin/sh

home_path="/home/donnie/Documents/Repos/triton-inference-server"
docker_img="nvcr.io/nvidia/tritonserver:20.06-py3"
#docker_img="tritonserver:latest"

docker run --rm --shm-size=1g --ulimit memlock=-1 \
        --ulimit stack=67108864 \
        -p 8000:8000 -p 8001:8001 -p 8002:8002 \
        -v $home_path/docs/examples/model_repository:/models \
        $docker_img tritonserver --model-repository=/models
```

2. run client container interactively: `docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.06-py3-clientsdk`

3. Inside the client container, run the following code:

`python image_client.py -i grpc -u localhost:8001 -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg`

This takes almost like **a minute** compared to REST api, which took like 1 sec or less.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

I am using an example model configuration from [triton provided model repo](https://github.com/NVIDIA/triton-inference-server/tree/master/docs/examples/model_repository/resnet50_netdef)

**Expected behavior**

Between REST api and gRPC , there should be no difference in communication time

**Comment by tanmayv25** [comment] 2020-07-23 18:56
There was a recent PR #1812 in master that improved the grpc server performance. That being said it should not be taking that long time. I followed the steps and below are my observations:

### HTTP Synchronous Operation
```
# time python image_client.py -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m1.116s
user    0m0.851s
sys     0m0.651s
```

### gRPC Synchronous Operation
```
# time python image_client.py -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg -i grpc -u localhost:8001
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m0.919s
user    0m0.720s
sys     0m0.647s
```

### HTTP Asynchronous Operation
```
# time python image_client.py -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg -a
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m1.092s
user    0m0.871s
sys     0m0.620s
```

### gRPC Asynchronous Operation
```
# time python image_client.py -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg -a -i grpc -u localhost:8001
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m0.927s
user    0m0.809s
sys     0m0.567s

```

Note: You must also see an improvement in performance with successive invocations to the client. The reason is in the first few requests the server will allocate the memory for the protobuf messages.

**Comment by DonnieKim411** [comment] 2020-07-23 19:08
Hi @tanmayv25 

Hmmm interesting Below is my observation

**gRPC Synchronous Operation**
```
# time python image_client.py -i grpc -u localhost:8001 -m resnet50_netdef -s INCEPTION /workspac
e/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    1m17.943s
user    0m0.810s
sys     0m0.603s
```

**HTTP Synchronous Operation**
```
# time python image_client.py -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m1.141s
user    0m0.955s
sys     0m0.546s
```


**gRPC Asynchronous Operation**
```
# time python image_client.py -i grpc -u localhost:8001 -m resnet50_netdef -s INCEPTION -a /works
pace/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    1m17.939s
user    0m0.761s
sys     0m0.648s
```


**HTTP Asynchronous Operation**
```
# time python image_client.py -m resnet50_netdef -s INCEPTION -a /workspace/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS

real    0m1.107s
user    0m0.906s
sys     0m0.585s
```

I am using branch r20.06. Would this be a problem? Should I switch to master? My understanding is that 20.06 is the v2 version and the latest one no?

**Comment by tanmayv25** [comment] 2020-07-23 20:21
Switching to master might not help. The slowdown is too large and the fix improves the performance for successive requests. Unfortunately, I was unable to reproduce the slowdown. But can you use the tracer in the server and share the summary? This might help in narrowing down the issue. Look [here](https://github.com/NVIDIA/triton-inference-server/blob/r20.06/docs/trace.rst).

**Comment by deadeyegoodwin** [comment] 2020-07-23 20:25
I think it is something related to your system. Notice how your user times are similar to what we see. It seems that for some reason your process isn't doing anything on the CPU but is taking alot of wall-clock time to finish.

**Comment by Tabrizian** [comment] 2020-07-23 20:28
I tried gRPC on my own system and it worked fine. There wasn't a noticeable difference between gRPC and HTTP on the default test case. I used the code on branch 20.06 and used Docker.

**Comment by DonnieKim411** [comment] 2020-07-24 16:52
@tanmayv25 

So I am working on setting up the tracer on the server but somehow, it does not write to the json file. Below is how i set it up:

```
#!/bin/sh

home_path="/home/donnie/Documents/Repos/triton-inference-server"
docker_img="nvcr.io/nvidia/tritonserver:20.06-py3"

# for server debugging purpose
docker run --rm --shm-size=1g --ulimit memlock=-1 \
        --ulimit stack=67108864 \
        -p 8000:8000 -p 8001:8001 -p 8002:8002 \
        -v $home_path/docs/examples/model_repository:/models \
        -v $home_path/trace:/tmp \        
        $docker_img tritonserver --model-repository=/models --trace-file=/tmp/trace.json --trace-rate=1 --trace-level=MAX
```

Then on my client side, I invoked 

```
# python /workspace/install/python/image_client.py -i grpc -u localhost:8001 -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg
Request 1, batch size 1
    0.777364 (504) = COFFEE MUG
PASS
```

I can invoke fine and I can also see `trace.json` under my `trace` directory (I made the directory), but there is nothing written in it

```
donnie@dirac ~/D/R/t/trace (r20.06)> pwd                                                                                                  (base) 
/home/donnie/Documents/Repos/triton-inference-server/trace
donnie@dirac ~/D/R/t/trace (r20.06)> cat trace.json                                                                                       (base) 
donnie@dirac ~/D/R/t/trace (r20.06)>                                                                                                      (base)
```

I made the trace rate to be 1 so that it can record every time i call... but it isn't doing any for me :(

**Comment by deadeyegoodwin** [comment] 2020-07-24 16:55
Before using the tracer you could just try running perf_client as described in the Optimization section of the documentation. That will give you a good breakdown of where time is being spent.

**Comment by DonnieKim411** [comment] 2020-07-24 22:31
@deadeyegoodwin 

Here are the summary of `perf_client`. Also I timed the whole operation on top of it

**HTTP Synchronous**
```
# time perf_client -m resnet50_netdef --percentile=95 --concurrency-range 2
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 2
  Client:
    Request count: 10
    Throughput: 2 infer/sec
    p50 latency: 947944 usec
    p90 latency: 949701 usec
    p95 latency: 950526 usec
    p99 latency: 950526 usec
    Avg HTTP time: 949043 usec (send/recv 292 usec + response wait 948751 usec)
  Server:
    Inference count: 12
    Execution count: 12
    Successful request count: 12
    Avg request latency: 946652 usec (overhead 6 usec + queue 472044 usec + compute input 80 usec + compute infer 474503 usec + compute output 19 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 2, throughput: 2 infer/sec, latency 950526 usec

real    0m18.559s
user    0m0.046s
sys     0m0.030s
```


**gRPC Synchronous**
```
# time perf_client -m resnet50_netdef --percentile=95 -i grpc -u localhost:8001 --concurrency-range 2
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 2
  Client:
    Request count: 10
    Throughput: 2 infer/sec
    p50 latency: 957557 usec
    p90 latency: 958420 usec
    p95 latency: 958588 usec
    p99 latency: 958588 usec
    Avg HTTP time: 956820 usec (send/recv 120 usec + response wait 956700 usec)
  Server:
    Inference count: 12
    Execution count: 12
    Successful request count: 12
    Avg request latency: 955445 usec (overhead 6 usec + queue 477268 usec + compute input 84 usec + compute infer 478067 usec + compute output 20 usec)

Inferences/Second vs. Client p95 Batch Latency
Concurrency: 2, throughput: 2 infer/sec, latency 958588 usec

real    1m35.722s
user    0m0.040s
sys     0m0.081s
```

So as you pointed out, as far as the inference time is concerned, they are taking about the same time... but the gRPC is taking a lot of wall time to finish the job. 

I know at this point, the issue is beyond the scope of triton server, but any guesses why i have such huge discrepancies between 2 protocols? Is it some hardware specific issue? memory ? i just want to know where i am stuck...

Also, idk if this helps, but when i performed the gRPC case, to get to this block of print outs took a lot of time:

```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 2
```

Once I got the above message, the rest of print outs were relatively quick.

**Comment by deadeyegoodwin** [comment] 2020-07-28 00:07
Some kind of network timeout perhaps? Do you have a different system where you can try to reproduce.

**Comment by DonnieKim411** [comment] 2020-07-29 17:16
@deadeyegoodwin 

Yes I have tried on a different machine and I can still reproduce this lag.

Btw, I found something weird. In order to see which line it takes most time I took a portion of a code from `simple_grpc_health_metadata.py` but **time** each execution of the line. :

```
import argparse
import datetime

import tritongrpcclient
from tritonclientutils import InferenceServerException

# set logger
import logging
logging.basicConfig(level=logging.DEBUG)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v',
                        '--verbose',
                        action="store_true",
                        required=False,
                        default=False,
                        help='Enable verbose output')
    parser.add_argument('-u',
                        '--url',
                        type=str,
                        required=False,
                        default='localhost:8001',
                        help='Inference server URL. Default is localhost:8001.')

    FLAGS = parser.parse_args()

    # measure time to create inference context
    start = datetime.datetime.now()
    try:
        triton_client = tritongrpcclient.InferenceServerClient(url=FLAGS.url,
                                                         verbose=FLAGS.verbose)
    except Exception as e:
        print("context creation failed: " + str(e))
        sys.exit()

    end = datetime.datetime.now()
    logging.info("inferance context creation duration: {}".format(end-start))
    
    model_name = 'simple'

    # Health

    # measure time to check whether the server is live or not
    start = datetime.datetime.now()
    if not triton_client.is_server_live(headers={'test': '1', 'dummy': '2'}):
        print("FAILED : is_server_live")
        sys.exit(1)

    end = datetime.datetime.now()
    logging.info("Task 1: checking whether the sever is live duration: {}".format(end-start))
    
    # measure time to check whether the server is live or not
    start = datetime.datetime.now()
    if not triton_client.is_server_ready():
        print("FAILED : is_server_ready")
        sys.exit(1)

    end = datetime.datetime.now()
    logging.info("Task 2: checking whether the sever is ready duration: {}".format(end-start))
```

And the following are the results:

```
# python grpc_time_executions.py 
INFO:root:inferance context creation duration: 0:00:00.008559
INFO:root:Task 1: checking whether the sever is live duration: 0:01:17.002229
INFO:root:Task 2: checking whether the sever is ready duration: 0:00:00.001082
```

context creation, i assume, does not communicate with the server. But the moment i communicate initially (Task 1, is server live), it takes like a 80 seconds to make a connection. Then for task 2, is server ready, it only takes 0.001 seconds. So there is a big overhead/delay just to make one connection. Once made, rest is super fast.

So, one might argue there is a network issue or our internet is slow as hell. But if that is the case, i would expect the same for HTTP communication. But I do not see that at all. HTTP calls are really fast compared to gRPC.

Then question becomes the following: how is the gRPC communication is set up? It looks like only if I request something from the server, it actually attempts to connect... then once the request is done, the connection stays alive... (hence the remainder of other tasks get computed super fast)?

I was digging around the code to understand how `tritongrpcclient.InferenceServerClient` is called, so I found the following: https://github.com/NVIDIA/triton-inference-server/blob/r20.06/src/clients/python/library/grpcclient.py#L146 . There, I can see that `grpc_service_pb2` module is imported from `tritongrpcclient`, but I cannot pinpoint where that module is. Can you show me where the source code of this module is?

**Comment by tanmayv25** [comment] 2020-07-30 18:55
`grpc_service_pb2` is the service file generated by gRPC from our service proto.  You can find it in container clientsdk.  `/usr/local/lib/python3.6/dist-packages/tritongrpcclient/`.

There appears to be similar issue reported on gRPC channel. See this discussion: https://github.com/grpc/grpc/issues/22260#issuecomment-630599796

**Comment by DonnieKim411** [comment] 2020-07-30 20:35
HA.... I am experiencing the exact same problem described in that thread.

https://github.com/grpc/grpc/issues/22260#issuecomment-596040814
> by the way, I also noticed that the python side gets slower and slower as the loop goes. It first took 2s to finish each iter, and after several tens of iters, it took about 6s, and after more iters, the latency can be as much as 30s.
> 
> By observing the output of command `htop`, I saw that one cpu core works at 100% during the transmission. Is this my configuration problem or some bug of python-grpc ?

When I request the model server _concurrently_ like 100 times, the latency gets larger and larger, so in the beginning it might take a couple of seconds, but later calls can get take like 30 seconds. I also saw one cpue core working at 100% during the communication.... 

So it sounds like now this is a problem of gRPC client side python package, not triton...

Should I close this thread then (since it is beyond the scope of triton package) ?

Also, do you guys have like s slack channel or some other means of communication? Sometimes I just wanna ask about APIs and github issue page is not suitable for that purpose.

**Comment by tanmayv25** [comment] 2020-08-03 19:01
I am closing this thread as the issue in not in the scope of Triton. Please follow up with the gRPC maintainers with your issue and observation. It looks like tied to certain system configurations and we have been unable to replicate it on our side.

> Also, do you guys have like s slack channel or some other means of communication? 

We don't have any such channels, but do try to maintain comprehensive documentation to our APIs. If something isn't clear then please raise a github issue.. It will be probably a bug or improvement in the documentation.

**Closed by tanmayv25** 2020-08-03 19:01 UTC

**Comment by stankwok1989** [comment] 2025-04-03 10:50
cool  hahah
