### ISSUE TITLE
async is too slow on http

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/triton-inference-server#1693] opened 2020-06-22 04:56 UTC
Same code for inference. But when using difference protocol method give me difference processing time.
```
results = []
        result_filenames = []
        request_ids = []
        image_idx = 0
        last_request = False
        user_data = UserData()
        sent_count=0

        while not last_request:
            input_filenames = []
            input_batch = []
            for idx in range(self.batch_size):
                input_filenames.append(idx)
                input_batch.append(image_data[image_idx])
                image_idx = (image_idx + 1) % len(image_data)
                if image_idx == 0:
                    last_request = True

            # Send request
            if not self.async_set:
                results.append(self.ctx.run(
                    {   self.input_names[0] : image_data },
                    {   self.output_names[0] : (InferContext.ResultFormat.RAW),
                        self.output_names[1] : (InferContext.ResultFormat.RAW),
                        self.output_names[2] : (InferContext.ResultFormat.RAW) },
                                self.batch_size))
                result_filenames.append(input_filenames)
            else:
                self.ctx.async_run(partial(self.completion_callback, input_filenames, user_data),
                                {   self.input_names[0] : image_data },
                                {   self.output_names[0] : (InferContext.ResultFormat.RAW),
                                    self.output_names[1] : (InferContext.ResultFormat.RAW),
                                    self.output_names[2] : (InferContext.ResultFormat.RAW) },
                                                        self.batch_size)
                sent_count += 1

        # For async, retrieve results according to the send order
        if self.async_set:
            processed_count = 0
            while processed_count < sent_count:
                (request_id, input_filenames) = user_data._completed_requests.get()
                results.append(self.ctx.get_async_run_results(request_id))
                result_filenames.append(input_filenames)
                processed_count += 1
```

for http:
![1](https://user-images.githubusercontent.com/53229746/85249818-f820ce80-b47e-11ea-9920-5fa54b64a0de.png)
for gRPC:
![Screenshot from 2020-06-22 10-35-29](https://user-images.githubusercontent.com/53229746/85249866-17b7f700-b47f-11ea-875a-134b2d3dcaae.png)

**Comment by CoderHam** [comment] 2020-07-02 20:49
@ThiagoMateo Which version of Triton did you use for this experiment?

**Comment by ThiagoMateo** [comment] 2020-07-10 09:40
hello @CoderHam . i don't use Triton, i use trtis:20.02-py3.
i have tried triton 20.03.1 but it is slower than trtis. i think it is new so i decide to skip it. =)

**Comment by CoderHam** [comment] 2020-07-20 19:29
Trtis transitioned to Triton. We are fixing any performance regressions. In the future releases of Triton the issue described here should not exist.

**Comment by deadeyegoodwin** [comment] 2020-08-04 15:57
Closing. Please try your example using the 20.08 version of Triton and reopen if the issue is still present.

**Closed by deadeyegoodwin** 2020-08-04 15:57 UTC
