### ISSUE TITLE
how to make TensorRT Optimization?

### ISSUE THREAD

**Issue by laohur** [NVIDIA/triton-inference-server#1378] opened 2020-04-28 11:31 UTC
20.03 docker onxx
fellow by [trt](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/optimization.html#onnx-with-tensorrt-optimization)
get 

> and get "Floating point exception (core dumped)" for "ONNX with TensorRT Optimization",

try to convert onnx float16 first:
node type not compatible

**Comment by deadeyegoodwin** [comment] 2020-04-28 15:25
Can you provide the model repository and all instructions we need to reproduce the failure.

**Comment by laohur** [comment] 2020-04-29 03:11
> 
> 
> Can you provide the model repository and all instructions we need to reproduce the failure.

actually,i do not know the right way. just append config.pbtext?

> steps:
> - from huggingface /transformers , pytorch load checkpoint and  eval, qps 300+
> -  convert  to onnx float32,
> -  set dynamic  and works, but qps=200
> -  try more optimize. append[ ONNX with TensorRT Optimization](https://docs.nvidia.com/deeplearning/sdk/triton-inference-server-master-branch-guide/docs/optimization.html#onnx-with-tensorrt-optimization) to config.pbtext
> - get error "Floating point exception (core dumped)"   
    # command: trtserver --model-repository=/workspace/model_repository --trace-level=MAX
I0429 03:08:36.390297 69 onnx_backend.cc:203] Creating instance multibert_0_gpu0 on GPU 0 (7.0) using model.onnx
Floating point exception (core dumped)

**Comment by GuanLuo** [comment] 2020-04-29 07:26
It's hard to tell if there is performance issue since you are comparing the performance across framework. It would be better if you have the performance of using Triton with the Pytorch model, or the performance of running the converted ONNX model natively to allow a more relevant comparison.

And it seems like the exception happens when loading the model, you should also try to run the ONNX model with ONNX Runtime directly to see whether TensorRT optimization succeeds and what the performance is, since Triton supports ONNX model via ONNX Runtime and thus capped by what ONNX Runtime can provide.

**Comment by deadeyegoodwin** [comment] 2020-04-30 17:14
@laohur If you give us the config.pbtxt and the onnx model itself that should be enough. An easy way to do this is to just zip or tar up the model repository containing this model and attach it.

**Comment by deadeyegoodwin** [comment] 2020-05-08 16:34
Closing. Please reopen after providing the requested model repository.

**Closed by deadeyegoodwin** 2020-05-08 16:34 UTC
