### ISSUE TITLE
CPU memory slowly increases when reusing an InferContext object for many times

### ISSUE THREAD

**Issue by jalola** [NVIDIA/triton-inference-server#1746] opened 2020-07-06 13:40 UTC
**Description**
I noticed that after few hours of sending 4 * 500k requests to Triton server (deployed with 4 Tensor RT models), the cpu memory increased about 2% of 32GB. I let it run for 1 day and the memory increased more. However, if I create InferContext object for every request, the memory usage didn't go up after sending same amount of requests.

I used http protocol and synchronous api call

**Triton Information**
Server: nvcr.io/nvidia/tritonserver:20.03-py3
Client: nvcr.io/nvidia/tritonserver:20.03-py3-clientsdk

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Here is the class I used for triton client to send request to server.
Note that I used 4 TritonClient objects for 4 models

```
import sys
import logging
import tensorrtserver.api as triton


def get_model_info(url, protocol, model_name, verbose=False):
    ctx = triton.ServerStatusContext(url, protocol, model_name, verbose)
    server_status = ctx.get_server_status()

    if model_name not in server_status.model_status:
        raise Exception("unable to get status for {}".format(model_name))

    status = server_status.model_status[model_name]
    config = status.config

    input_nodes = config.input
    output_nodes = config.output

    return input_nodes, output_nodes


class TritonClient:
    def __init__(self, url, protocol, model_name, model_version, verbose=False):
        self.url = url
        self.protocol = triton.ProtocolType.from_str(protocol)
        self.model_name = model_name
        self.model_version = model_version
        input_nodes, output_nodes = get_model_info(self.url, self.protocol, self.model_name)
        self.input_name = input_nodes[0].name
        self.output_names = []
        for output in output_nodes:
            self.output_names.append(output.name)
        self.trt_ctx = triton.InferContext(self.url, self.protocol, self.model_name, self.model_version, verbose=verbose) 
       # **move this line to do_inference will resolve the memory increasing**

        self.output_dict = {}
        for i in range(len(self.output_names)):
            self.output_dict[self.output_names[i]] = triton.InferContext.ResultFormat.RAW

    def do_inference(self, x: list, keep_name=False):
        batch_size = len(x)
        try:
            output = self.trt_ctx.run({self.input_name: x}, self.output_dict, batch_size)
        except triton.InferenceServerException as e:
            logging.info(e)
            sys.exit()

        if not keep_name:
            return [output[self.output_names[i]] for i in range(len(self.output_names))]
        return output

```

**Expected behavior**
CPU memory should not increase if reusing same InferContext object for different requests

**Comment by deadeyegoodwin** [comment] 2020-07-07 20:11
Perhaps there is a small memory leak in the clients. There was a small leak that was just fixed with #1709 but that was for an async case.
I suggest you try r20.06-v1 and see if you still see the issue. And even better you should move the V2 clients and use r20.06 as that is the future direction for Triton.

**Comment by jalola** [comment] 2020-07-08 01:16
Hi, thanks for your reply. Yeh, I have seen that issue but I checked the changes and it was for async fix only.

I would like to use V2 client from the beginning but I have seen the README saying that V2 is still under development so that's why I chose V1.

> Version 2 of Triton is beta quality, so you should expect some changes to the server and client protocols and APIs.

I will try V2 and see how it goes. Thanks

**Comment by jalola** [comment] 2020-07-08 02:36
Btw, I have couple of questions
1. Why are the size of both 20.06-py3 (8.13GB) and 20.06-py3-clientsdk (6.08G) bigger than previous one?
Previous ones were <7GB and 5.5GB respectively.

2. Can I use server version 20.03 and client version 20.06-v1 or 20.06 v2?

**Comment by deadeyegoodwin** [comment] 2020-07-08 03:23
The growth is mostly due to the underlying frameworks growing. We are moving Triton to a arch where it will be easier to remove unwanted frameworks from the container. You can actually do it now by using a multistage build and pulling over only the parts you want... but it can be tricky if you are familiar with Docker.

20.03 is only V1, so you could use 20.06-v1 client with it. Once V2 matures a little more we will take it out of beta and will then have some backwards compatibility guarantees for V2, but for now you should use V2 clients and server from the same release.

**Comment by DonnieKim411** [comment] 2020-07-20 17:50
@jalola Have you tried v2 version with async call yet? Do you still see increase in CPU memory ? I assume by CPU memory, you meant RAM, right? Not CPU cache memory but RAM memory.

Also do you mind which version of tensorflow you are using?

Just for my little background, I used tensorflow server with tensorflow 2.0.0 and I saw the increase in memory usage every time I request the inference... and there is indeed an open issue on it too but nobody bothered to fix (or the thread is dead). So I am trying to switch to triton just to see if it is memory leak free. But it does sound like triton also suffers a memory leak problem although there was a PR #1709 fixing an async call memory leak problem. 

I am quite convinced, at this point, that there is an internal memory management problem within tensorflow framework...

**Comment by jalola** [comment] 2020-07-21 01:57
Hi @DonnieKim411 ,
That is RAM.

Btw, all of my models are TensorRT. And I found a quick fix by creating InferenceContext for every request.
For your case, it is unclear that the leak is because of Triton server or client. You need to verify it first.

**Comment by DonnieKim411** [comment] 2020-07-21 20:12
Hi @jalola,

It is not so clear which side is the culprit of memory leak issue... but what i consistently see is that as i request the inference repeatedly _over_ time, I see memory build up on the server. So I the "result" is the memory build up on the server.

I see that you are using TensorRT to do it. The way I did for tensorflow serving was converting it into protobuf, then call via gRPC. Maybe I will give a shot to TensorRT. I will follow up on this as I progress.

**Comment by jalola** [comment] 2020-07-22 01:47
- To know which side is the culprit, you can start the server serving your TF model in 1 docker container and start clients in another docker container. Then run them for a time and open some Ram monitoring (htop). Close each of them at different time and you will know which side has the leak.

- About the script, you can prefer the class I sent on the first comment.
To use for each model, just create triton client:
```
triton_client = TritonClient(triton_url, triton_protocol, 'model_name', -1)

for loop:
    triton_client.do_inference(numpy_data)
```
btw, triton_protocol = "http"

**Comment by CoderHam** [comment] 2020-07-22 18:25
@jalola I would recommend you use the same version of the client with the server and try the same with 20.06-v1 and 20.06-v2.

**Comment by DonnieKim411** [comment] 2020-08-03 00:28
@jalola Hi again, so I have separated out between client and server but on the server side, I am seeing a gradual memory build up. The way I tested is the following. On 1 computer, I have a client docker, and on the 2nd computer, I have a server docker. Then, I requested 256 images (I enabled a batch option) per request, and I requested concurrently 90 times. And I repeated this process 3 times over time. On the client, I can see memory spiking up but quickly release, indicating on the client side, there is no memory leak:

This is client system load + memory profile:
![image](https://user-images.githubusercontent.com/23262857/89135725-29b49d00-d4f5-11ea-9df1-07bfab1c541e.png)


However, on the server side, I can clearly see a memory build up:

![image](https://user-images.githubusercontent.com/23262857/89135698-f83bd180-d4f4-11ea-9d5a-180111ce0eb1.png)


Below, is my code how I built the server:

```

class ToyClientHttp():
    """
    Http Toy Client
    """

    def __init__(self, flags):

        try:
            self.triton_client = tritonhttpclient.InferenceServerClient(url=flags.url,
                                                            verbose=flags.verbose,
                                                            connection_count=100)
        except Exception as e:
            print("context creation failed: " + str(e))
            sys.exit()

        # Make sure the model matches our requirements, and get some
        # properties of the model that we need for preprocessing
        try:
            model_metadata = self.triton_client.get_model_metadata(
                model_name=flags.model_name, model_version=flags.model_version)
        except InferenceServerException as e:
            print("failed to retrieve the metadata: " + str(e))
            sys.exit(1)

        try:
            model_config = self.triton_client.get_model_config(
                model_name=flags.model_name, model_version=flags.model_version)
        except InferenceServerException as e:
            print("failed to retrieve the config: " + str(e))
            sys.exit(1)

        max_batch_size, input_name, output_name, input_dtype = parse_model_http(
            model_metadata, model_config)

        self.max_batch_size = max_batch_size
        self.input_name = input_name
        self.output_name = output_name
        self.input_dtype = input_dtype

    def infer(self, input_data, output_data, flags, sent_count):
        """
        infer
        """

        # infer asynchronously
        return self.triton_client.async_infer( 
                                            flags.model_name, 
                                            input_data,
                                            request_id=str(sent_count),
                                            model_version=flags.model_version,
                                            outputs=output_data)

def run(flags):

    random_img = np.random.uniform(low=0.0, high=1.0, size=(flags.batch_size,150,40,1)).astype(np.float32)
   
    # client = ToyClient('auroraaidev:8500')
    responses = []

    # Holds the handles to the ongoing HTTP async requests.
    async_requests = []

    sent_count = 0

    # Send request over batch
    try:
        for inputs, outputs in requestGenerator(random_img, 
                                                triton_client.input_name, 
                                                triton_client.output_name, 
                                                triton_client.input_dtype, 
                                                flags):

            # initialize the toy client http
            triton_client = ToyClientHttp(flags)
            
            async_requests.append(triton_client.infer(inputs, outputs, flags, sent_count))
            sent_count += 1

    except InferenceServerException as e:
        print("inference failed: " + str(e))
        sys.exit(1)

    # Collect results from the ongoing async requests
    # for HTTP Async requests.

    for async_request in async_requests:

        result = async_request.get_result()
        responses.append(result.as_numpy(triton_client.output_name))

```

And to request 256 images 90 times conccurently, I made a simple script as the following:

```
#!/bin/bash

concurrent_call=""

for i in $(seq "$2");do
        command='python http_call_tester.py --url=dirac:8000 --batch_size '"$1 & "
        concurrent_call+=$command
done

# echo $concurrent_call

# evluate the expression
eval $concurrent_call

wait
echo jobs done!
```

and on client side, i would call `./concurrent_tester.sh 256 90`.

I am using 20.06 btw for both client and server

**Comment by jalola** [comment] 2020-08-05 01:23
If you are sure that the problem is from server side, then I suggest you to double check by perf_client. It is very useful. You can just send a bunch of request with different options to servers and see if memory of server side still increases or not.

Doc: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/perf_client.html?highlight=perf

Example:
```perf_client -m model_name -b 8 -t 15 -u localhost:8888```
b: batch_size
t: number of concurrent clients sending request

I think you may try with and without --async. The leaking may be due to asynchronous requests.
Check `perf_client -h` for more options

**Comment by DonnieKim411** [comment] 2020-08-05 04:28
@jalola 
Hey, thanks for the suggestion. I will certainly take a look.

One more question. When you use your model server (which has 4 models), how do you handle concurrent client calls? Say, there are 10 users all of the sudden simultaneously request model inference for all those 4 models, do u not see any increase in memory (on the server side)? That's what i am suffering now. The memory builds up only if I have those simultaneous requests. It is true that I am doing async call so that might be an issue as well... but just wanted to know...

**Comment by jalola** [comment] 2020-08-05 05:39
I attached an image to show the structure of 4 models. And I can start multiple clients just like 10 users you mentioned and I don't see any increase memory. Btw, the concurrency and running batch are handled by Triton, I don't need to do extra step. Here is one of my model setting:

```
name: "name"
platform: "tensorrt_plan"
max_batch_size: 8
dynamic_batching {
    preferred_batch_size: [ 4, 8 ]
    max_queue_delay_microseconds: 1000
}
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
input [
  {
    name: "model_input"
    data_type: TYPE_FP32
    dims: [3, 112, 112]
  }
]
output [
  {
    name: "model_output"
    data_type: TYPE_FP32
    dims: [1]
    reshape: { shape: [] }
  }
]
```

As I mentioned, if you use perf_client, you can simulate concurrent client calls easily.
You just need to start your models and get its url, then you start this docker image:
nvcr.io/nvidia/tritonserver:20.06-py3-clientsdk and run the command as I showed above.

<img width="1108" alt="Screenshot 2020-08-05 at 1 27 16 PM" src="https://user-images.githubusercontent.com/1896808/89375229-d6726280-d71f-11ea-983c-f81bd0be8624.png">

**Comment by CoderHam** [comment] 2020-08-05 17:52
@jalola @DonnieKim411 I was unable to reproduce the increase in physical memory usage when re-using InferContext. I use the same script @jalola mentioned in the creation of the ticket. I make 10000 requests using the same InferContext. I repeat the same while creating new InferContext. The increase in physical memory usage is constant in both cases. Even changing from 10k to 20k or 30k does not increase physical memory usage. 

Are you sure you are using RES and not VIRT memory in your testing? I do not see a memory leak on either client or server side.

**Comment by CoderHam** [comment] 2020-08-06 00:02
Please try with 20.07 and re-open if you still see the issue.

**Closed by CoderHam** 2020-08-06 00:02 UTC

**Comment by yushcs** [comment] 2021-04-20 11:38
@DonnieKim411 Hi, i met the same problem, did you solve it?
