### ISSUE TITLE
Memory leak when running simple_cuda_shm_client?

### ISSUE THREAD

**Issue by maaikez** [NVIDIA/triton-inference-server#1636] opened 2020-06-09 08:11 UTC
**Description**
When running simple_cuda_shm_client in valgrind, it reports memory leaks: 

==1012== HEAP SUMMARY:
==1012==     in use at exit: 8,577,539 bytes in 14,429 blocks
==1012==   total heap usage: 25,221 allocs, 10,792 frees, 45,305,185 bytes allocated
==1012== 
==1012== LEAK SUMMARY:
==1012==    definitely lost: 0 bytes in 0 blocks
==1012==    indirectly lost: 0 bytes in 0 blocks
==1012==      possibly lost: 103,352 bytes in 797 blocks
==1012==    still reachable: 8,474,187 bytes in 13,632 blocks
==1012==         suppressed: 0 bytes in 0 blocks

**Triton Information**
I use Triton server 1.12.0 / 20.03. I use the nvcr.io/nvidia/tritonserver:20.03-py3 container and start it with: 
docker run --name tensorrt_inferenceserver \
    --detach \
    --gpus=all \
    --restart always \
    --shm-size=1g \
    --ulimit memlock=-1 \
    --ulimit stack=67108864 \
    -p8000:8000 -p8001:8001 -p8002:8002 \
    -v /data/models:/models \
    nvcr.io/nvidia/tritonserver:20.03-py3 \
    trtserver \
    --model-store=/models

I use the pre built client libraries for Ubuntu 18.04 (so I did not build the simple_cuda_shm_client myself). But I also created my own program based on this example, which also gives memory leaks. I use the grpc protocol.

I run the program from:
- A docker container based on nvidia/cuda:10.1-devel-ubuntu18.04
- My own pc, which runs ArchLinux.

**To Reproduce**
- Download the 'simple' model from https://github.com/NVIDIA/triton-inference-server/tree/r20.03/docs/examples/model_repository 
- Put the model in the model directory
- Start the tritonserver container
- Start the nvidia cuda ubuntu container
- Download the client package (https://github.com/NVIDIA/triton-inference-server/releases/download/v1.12.0/v1.12.0_ubuntu1804.clients.tar.gz) containing `simple_cuda_shm_client and unpack.
- Run the `simple_cuda_shm_client` with valgrind from within the docker container and / or on the host. 

**Expected behavior**
No valgrind memory leak suggestions when running the program in valgrind.

Is there a way to prevent this?

**Comment by CoderHam** [comment] 2020-06-09 18:26
Thank you for this repro. We'll look into fixing this for the next release

**Comment by CoderHam** [comment] 2020-06-26 20:14
I was able to reproduce this error. We will be fixing this shortly.

**Comment by maaikez** [comment] 2020-06-27 15:24
That's great. Can you already say something about how to prevent this?

**Comment by CoderHam** [comment] 2020-06-29 18:04
The issue was caused by calling delete instead of free on a malloced region. From my understanding and after confirming [here ](http://pages.cs.wisc.edu/~bart/537/valgrind.html)and [here ](https://stackoverflow.com/questions/3840582/still-reachable-leak-detected-by-valgrind)I believe these both are not harmful memory leaks and normally they do not have the potential for heap exhaustion. I am going ahead and closing this issue for now,

**Closed by CoderHam** 2020-06-29 18:04 UTC
